---
- name: Give internet
  hosts: OSEv3
  tasks:
    - name: Add gateway
      command: nmcli con mod eth0 ipv4.gateway 192.168.122.1 

    - name: Add name server
      command: nmcli con mod eth0 ipv4.dns 192.168.122.1 

    - name: Restart network 
      command: systemctl restart network

    - name: Restart NetworkManager
      command: systemctl restart NetworkManager

